# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: deltebre
          POSTGRES_PASSWORD: circleci
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coverage
            pip install flake8
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: flake8
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run manage.py test -v 2
      - run:
          name: coverage report
          command: |
            . venv/bin/activate
            coverage report -m
      - store_artifacts:
          path: test-reports
          destination: test-reports