# Generated by Django 2.0.4 on 2018-06-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('votes', models.BigIntegerField()),
                ('percentage', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('image', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('budgeted', models.FloatField()),
                ('real', models.FloatField()),
                ('difference', models.FloatField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='GenderAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('age', models.IntegerField()),
                ('genre', models.BooleanField()),
                ('color', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200)),
                ('chapter', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
                ('real', models.FloatField()),
                ('difference', models.FloatField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TuristicService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
